apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "application.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /{{ include "application.name" . }}/(.*)
        pathType: ImplementationSpecific
        # pathType: Prefix
        backend:
          service:
            name: {{ include "application.name" . }}
            port:
              number: {{ .Values.service.port }}