apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.name" . }}
data:
  SERVICE_NAME:                             {{ .Values.service.name | quote}}
  SERVICE_PORT:                             {{ .Values.service.port | quote }}
  PGMINPOOLSIZE:                            {{ .Values.PGMINPOOLSIZE | quote}}