apiVersion: v1
kind: ConfigMap
metadata:
  name: lock-manager-configmap
data:
  SERVICE_NAME:                             {{ .Values.service.name }}
  TARGET_SERVICE_URL:                       {{ .Values.TARGET_SERVICE_URL | quote}} 
  PGMINPOOLSIZE:                            {{ .Values.PGMINPOOLSIZE | quote}}