{{- if or (eq .Values.ENVIRONMENT "dev")}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-dev-lock-manager-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  provider:
    fake:
      data:
        - key: {{ .Values.externalSecrets.vaultPaths.db }}
          value: |
            {
              "hostnames": "{{ .Values.PGHOST }}",
              "port": "{{ .Values.PGPORT }}",
              "username": "{{ .Values.PGUSER }}"
              "password": "{{ .Values.PGPASSWORD }}",
              "database": "{{ .Values.PGDATABASE }}",
            }

{{- end }}