{{- if or (eq .Values.ENVIRONMENT "dev")}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev-lock-manager-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
# spec:
#   provider:
#     fake:
#       data:
#         - key: secret/devs/dev/postgres/dpt
#           value: |
#             {
#               "database": "{{ .Values.PG_DATABASE }}",
#               "hostnames": "{{ .Values.PG_HOST }}",
#               "port": "{{ .Values.PG_PORT }}",
#               "username": "{{ .Values.PG_USER }}"
#               "password": "{{ .Values.PG_PASSWORD }}",
#             }

{{- end }}