{{- if (eq (.Values.PIT_LOCK_MANAGER_DEPLOY_DEV_SECRET_STORE | toString) "true")}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "application.name" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1" 
spec:
  provider:
    fake:
      data:
        - key: {{ .Values.EXTERNAL_SECRET_DB_PATH }}
          value: |
            {
              "hostnames": "{{ .Values.PGHOST }}",
              "port": "{{ .Values.PGPORT }}",
              "username": "{{ .Values.PGUSER }}"
              "password": "{{ .Values.PGPASSWORD }}",
              "database": "{{ .Values.PGDATABASE }}",
            }
{{- end }}