apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lock-manager-external-secret
  
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: vault-{{ or (eq .Values.ENVIRONMENT "dev") | ternary "dev-lock-manager-secret" "backend"}}
    kind: SecretStore
  target:
    name: lock-manager-auth
  data:
    - secretKey: PG_DATABASE
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: database
    - secretKey: PG_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: hostnames
    - secretKey: PG_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: password
    - secretKey: PG_PORT
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: port
    - secretKey: PG_USER
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: username