apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "application.name" . }}-external-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1" 
spec:
  refreshInterval: {{ .Values.EXTERNAL_SECRET_REFRESH | quote }}
  secretStoreRef:
    name: {{ .Values.SECRET_STORE_NAME }}
    kind: SecretStore
  target:
    name: {{ include "application.name" . }}
  data:
    - secretKey: PGHOST
      remoteRef:
        key: {{ .Values.EXTERNAL_SECRET_DB_PATH }}
        property: hostnames
    - secretKey: PGPORT
      remoteRef:
        key: {{ .Values.EXTERNAL_SECRET_DB_PATH }}
        property: port
    - secretKey: PGUSER
      remoteRef:
        key: {{ .Values.EXTERNAL_SECRET_DB_PATH }}
        property: username
    - secretKey: PGPASSWORD
      remoteRef:
        key: {{ .Values.EXTERNAL_SECRET_DB_PATH }}
        property: password
    - secretKey: PGDATABASE
      remoteRef:
        key: {{ .Values.EXTERNAL_SECRET_DB_PATH }}
        property: database