apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lock-manager-external-secret
  
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: vault-{{ or (eq .Values.ENVIRONMENT "dev") | ternary "dev-lock-manager-secret" "backend"}}
    kind: SecretStore
  target:
    name: lock-manager-auth
  data:
    - secretKey: PGHOST
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: hostnames
    - secretKey: PGPORT
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: port
    - secretKey: PGUSER
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: username
    - secretKey: PGPASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: password
    - secretKey: PGDATABASE
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: database