apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "application.name" . }}-external-secret
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: vault-{{ eq .Values.ENVIRONMENT "dev" | ternary "dev-lock-manager" "backend"}}
    kind: SecretStore
  target:
    name: {{ include "application.name" . }}
  data:
    - secretKey: PGHOST
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: hostnames
    - secretKey: PGPORT
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: port
    - secretKey: PGUSER
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: username
    - secretKey: PGPASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: password
    - secretKey: PGDATABASE
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: database