{{- if or (eq .Values.ENVIRONMENT "dev") (hasPrefix "sit-" .Release.Namespace) (hasPrefix "pit-" .Release.Namespace)}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-fake-scylla
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  provider:
    fake:
      data:
        - key: {{ .Values.externalSecrets.vaultPaths.db }}
          value: |
            {
              "database": "{{ .Values.PG_DATABASE }}",
              "hostnames": "{{ .Values.PG_HOST }}",
              "port": "{{ .Values.PG_PORT }}",
              "username": "{{ .Values.PG_USER }}",
              "password": "{{ .Values.PG_PASSWORD }}"
            }
        # - key: {{ .Values.externalSecrets.vaultPaths.dbAdmin }}
        #   value: |
        #     {
        #       "database": "{{ .Values.PG_ADMIN_DATABASE }}",
        #       "hostnames": "{{ .Values.PG_HOST }}",
        #       "port": "{{ .Values.PG_PORT }}",
        #       "username": "{{ .Values.PG_ADMIN_USER }}",
        #       "password": "{{ .Values.PG_ADMIN_PASSWORD }}"
        #     }
       
{{- end }}