apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "application.name" . }}-external-secret-admin
  labels:
    {{- include "application.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: vault-{{ or (eq .Values.ENVIRONMENT "dev") (hasPrefix "sit-" .Release.Namespace) (hasPrefix "pit-" .Release.Namespace) | ternary "fake-scylla" "backend"}}
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-auth-admin
  data:
    - secretKey: PG_ADMIN_DATABASE
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.dbAdmin }}
        property: database    
    - secretKey: PG_DATABASE
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }}
        property: database
    - secretKey: PG_HOST
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.dbAdmin }}
        property: hostnames
    - secretKey: PG_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.dbAdmin }}
        property: password
    - secretKey: PG_PORT
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.dbAdmin }}
        property: port
    - secretKey: PG_USER
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.dbAdmin }}
        property: username
{{- if eq .Values.TALOS_MIGRATION_CREATE_DB "true" }}
    - secretKey: PG_APP_USER
      remoteRef:
        key: {{ .Values.externalSecrets.vaultPaths.db }} # this is not a typo, intentionally using app user
        property: username
{{- end }}