apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application.name" . }}
data:
  SERVICE_NAME: {{ .Values.SERVICE_NAME | quote }}
  BROWNIE_NODE_OPTIONS: {{ .Values.BROWNIE_NODE_OPTIONS | quote }}
  DRY_RUN: {{ .Values.DRY_RUN | quote }}
  RETENTION_PERIOD: {{ .Values.RETENTION_PERIOD | quote }}
  TIMESTAMP_PATTERN: {{ .Values.TIMESTAMP_PATTERN | quote }}