{{- if (eq (.Values.BROWNIE_DEPLOY_DEV_SECRET_STORE | toString) "true")}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "application.name" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  provider:
    fake:
      data:
      {{- if not .Values.POSTGRESQL_CONFIG_NAMES }}
        - key: {{ .Values.EXTERNAL_SECRET_DB_PATH }}
          value: |
            {
              "hostnames": "{{ .Values.PGHOST }}",
              "port": "{{ .Values.PGPORT }}",
              "username": "{{ .Values.PGUSER }}"
              "password": "{{ .Values.PGPASSWORD }}",
              "database": "{{ .Values.PGDATABASE }}"
            }
      {{- end }}
      {{- range $cfgName := .Values.POSTGRESQL_CONFIG_NAMES }}
        - key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}-{{$cfgName | lower}}
          value: |
            {
              "hostnames": {{ (index $.Values (printf "%s_PGHOST" ($cfgName | upper))) | quote }},
              "port": {{ (index $.Values (printf "%s_PGPORT" ($cfgName | upper))) | quote }},
              "username": {{ (index $.Values (printf "%s_PGUSER" ($cfgName | upper))) | quote }},
              "password": {{ (index $.Values (printf "%s_PGPASSWORD" ($cfgName | upper))) | quote }},
              "database": {{ (index $.Values (printf "%s_PGDATABASE" ($cfgName | upper))) | quote }}
            }
      {{- end }}
      {{- if not .Values.KAFKA_CONFIG_NAMES }}
        - key: {{ .Values.EXTERNAL_SECRET_KAFKA_PATH }}
          value: |
            {
              "hostnames": {{ .Values.KAFKA_BROKERS | quote }},
              "port": {{ .Values.KAFKA_PORT | quote }},
              "username": {{ .Values.KAFKA_USERNAME | quote }},
              "password": {{ .Values.KAFKA_PASSWORD | quote }}
            }
      {{- end }}
      {{- if .Values.KAFKA_CONFIG_NAMES }}
      {{- range $cfgName := .Values.KAFKA_CONFIG_NAMES }}
        - key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}-{{$cfgName | lower}}
          value: |
            {
              "hostnames": {{ (index $.Values (printf "%s_KAFKA_BROKERS" ($cfgName | upper))) | quote }},
              "port": {{ (index $.Values (printf "%s_KAFKA_PORT" ($cfgName | upper))) | quote }},
              "username": {{ (index $.Values (printf "%s_KAFKA_USERNAME" ($cfgName | upper))) | quote }},
              "password": {{ (index $.Values (printf "%s_KAFKA_PASSWORD" ($cfgName | upper))) | quote }}
            }
      {{- end }}
      {{- end }}
{{- end }}