apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "application.name" . }}-external-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  refreshInterval: {{ .Values.EXTERNAL_SECRET_REFRESH | quote }}
  secretStoreRef:
    name: {{ .Values.SECRET_STORE_NAME }}
    kind: SecretStore
  target:
    name: {{ include "application.name" . }}
  data:
  {{- if not .Values.POSTGRESQL_CONFIG_NAMES }}
    - secretKey: PGHOST
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}
        property: hostnames
    - secretKey: PGPORT
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}
        property: port
    - secretKey: PGUSER
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}
        property: username
    - secretKey: PGPASSWORD
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}
        property: password
    - secretKey: PGDATABASE
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}
        property: database
  {{- end }}
  {{- if .Values.POSTGRESQL_CONFIG_NAMES }}
  {{- range $cfgName := .Values.POSTGRESQL_CONFIG_NAMES }}
    - secretKey: {{ $cfgName | upper }}_PGHOST
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}-{{ $cfgName | lower }}
        property: hostnames
    - secretKey: {{ $cfgName | upper }}_PGPORT
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}-{{ $cfgName | lower }}
        property: port
    - secretKey: {{ $cfgName | upper }}_PGUSER
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}-{{ $cfgName | lower }}
        property: username
    - secretKey: {{ $cfgName | upper }}_PGPASSWORD
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}-{{ $cfgName | lower }}
        property: password
    - secretKey: {{ $cfgName | upper }}_PGDATABASE
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_DB_PATH }}-{{ $cfgName | lower }}
        property: database
  {{- end }}
  {{- end }}
  {{- if not .Values.KAFKA_CONFIG_NAMES }}
    - secretKey: KAFKA_BROKERS
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}
        property: hostnames
    - secretKey: KAFKA_PORT
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}
        property: port
    - secretKey: KAFKA_USERNAME
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}
        property: username
    - secretKey: KAFKA_CLIENT_ID
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}
        property: username # intentionally use username  
    - secretKey: KAFKA_PASSWORD
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}
        property: password
  {{- end }}
  {{- if .Values.KAFKA_CONFIG_NAMES }}
  {{- range $cfgName := .Values.KAFKA_CONFIG_NAMES }}
    - secretKey: {{ $cfgName }}_KAFKA_BROKERS
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}-{{ $cfgName | lower }}
        property: hostnames
    - secretKey: {{ $cfgName | upper }}_KAFKA_PORT
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}-{{ $cfgName | lower }}
        property: port
    - secretKey: {{ $cfgName | upper }}_KAFKA_USERNAME
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}-{{ $cfgName | lower }}
        property: username
    - secretKey: {{ $cfgName | upper }}_KAFKA_CLIENT_ID
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}-{{ $cfgName | lower }}
        property: username        
    - secretKey: {{ $cfgName | upper }}_KAFKA_PASSWORD
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_KAFKA_PATH }}-{{ $cfgName | lower }}
        property: password
  {{- end }}
  {{- end }}
  {{- if not .Values.ELASTICSEARCH_CONFIG_NAMES }}
    - secretKey: ELASTICSEARCH_URL
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_ELASTICSEARCH_PATH }}
        property: url
    - secretKey: ELASTICSEARCH_USERNAME
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_ELASTICSEARCH_PATH }}
        property: username
    - secretKey: ELASTICSEARCH_PASSWORD
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_ELASTICSEARCH_PATH }}
        property: password
  {{- end }}
  {{- if .Values.ELASTICSEARCH_CONFIG_NAMES }}
  {{- range $cfgName := .Values.ELASTICSEARCH_CONFIG_NAMES }}
    - secretKey: {{ $cfgName | upper }}_ELASTICSEARCH_URL
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_ELASTICSEARCH_PATH }}-{{ $cfgName | lower }}
        property: url
    - secretKey: {{ $cfgName | upper }}_ELASTICSEARCH_USERNAME
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_ELASTICSEARCH_PATH }}-{{ $cfgName | lower }}
        property: username
    - secretKey: {{ $cfgName | upper }}_ELASTICSEARCH_PASSWORD
      remoteRef:
        key: {{ $.Values.EXTERNAL_SECRET_ELASTICSEARCH_PATH }}-{{ $cfgName | lower }}
        property: password
  {{- end }}
  {{- end }}