# workflow_call to build the rust app
name: npm_build_and_test

on: workflow_call

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Setup node
          uses: actions/setup-node@v3
          with:
            node-version: 18
            check-latest: true
        - name: npm install, build and test lock-manager
          run: sh bin/npm-build.sh lock-manager
